### ISSUE TITLE
Change color of tags text and bullets

### ISSUE THREAD

**Issue by grant-shillings** [whyt-byte/Blue-Topaz_Obsidian-css#150]
Hi, I am using the styles editor plugin, and can't find how to change the color of text for tags and the color of bullet points. Can you explain how to do that?

**Comment by whyt-byte** [comment]
I have added an option to change the text of tags in Style Settings. For the option to change the color of bullet points, I think maybe it's too detailed for users. So at present, you can use the following code to create a snippet. Have fun!

```css
span.list-bullet, 
li::marker,
.cm-formatting.cm-formatting-list.cm-formatting-list-ul {
  color: red;
}
```
