### ISSUE TITLE
可以把屏幕最右侧的那个竖栏，自动隐藏吗？

### ISSUE THREAD

**Issue by aQuaYi** [whyt-byte/Blue-Topaz_Obsidian-css#2]
可以把屏幕最右侧的那个竖栏，自动隐藏吗？
我看别的主题可以的。
我的屏幕很小，希望可以自动隐藏掉，好节约空间。
万分感谢。

**Comment by whyt-byte** [comment]
好的。我也会进行功能更新。为方便你使用其他主题时也能隐藏右侧边栏，请见以下代码。

```
/* Hide right side bar */
.workspace-ribbon.mod-right:not(:hover) {
  width: 0px;
  transition: all 300ms ease-in-out;
}
  
.workspace-split.mod-right-split {
  margin-right: 0px;
}
```

> 可以把屏幕最右侧的那个竖栏，自动隐藏吗？
> 我看别的主题可以的。
> 我的屏幕很小，希望可以自动隐藏掉，好节约空间。
> 万分感谢。

**Comment by aQuaYi** [comment]
@whyt-byte 非常感谢。

**Comment by whyt-byte** [comment]
> @whyt-byte 非常感谢。

不客气，主题已更新，请在软件“社区主题”中再次点击“使用”更新主题，或直接从GitHub里下载覆盖原文件。如果发现bug或者功能方面的需求，也请提出，谢谢。

**Comment by aQuaYi** [comment]
我倒是一点不成熟的小建议。

https://github.com/jarodise/Dracula-for-Obsidian.md/blob/master/obsidian.css

像这个主题，标题大小和字体放在文件开头。

很方便我们这些小白修改。


```css
:root
{
    --font-size-normal:              20px;
    --font-size-code:                22px;
    --font-size-side-dock:           20px;
    --font-size-side-dock-title:     20px;
    --font-size-status-bar:          18px;
    --font-size-h1:                  28px;
    --font-size-h2:                  27px;
    --font-size-h3:                  26px;
    --font-size-h4:                  25px;
    --font-size-h5:                  24px;
    --font-size-h6:                  23px;
    --font-family-editor:            "JetBrains Mono", 文泉驿等款微米黑, monaco;
    --font-family-preview:           "JetBrains Mono", 文泉驿等款微米黑, monaco;
} 
```
