### ISSUE TITLE
如何修改「设置菜单」字体和字体大小

### ISSUE THREAD

**Issue by orivee** [whyt-byte/Blue-Topaz_Obsidian-css#251]
尝试改变 Style Settings 插件中字体设置，没有找到能改变设置菜菜单字体的选项。

感觉默认字体有点太大了，想调小一点，顺带想改一下设置菜菜单字体 ^_~

![obsidian-setting](https://user-images.githubusercontent.com/6487389/159261412-4376e22c-1978-4ef9-8b89-f136ae0997ad.png)

**Comment by whyt-byte** [comment]
style settings没有提供该选项，可以自己写css片段更改，建议教程如下：https://forum-zh.obsidian.md/t/topic/180

**Comment by orivee** [comment]
> style settings没有提供该选项，可以自己写css片段更改，建议教程如下：[forum-zh.obsidian.md/t/topic/180](https://forum-zh.obsidian.md/t/topic/180)

感谢，也已经找到相应的设置元素。方法如下：

左边的菜单栏通过 `vertical-tab-nav-item` 属性控制，调整了 `padding`、`font-size` 和 `font-family` 。

![menu-pane](https://user-images.githubusercontent.com/6487389/159390922-02be866e-c443-4eb5-abcd-2518f555c8a1.png)

菜单右边其中的主题设置通过 `setting-item-name` 属性控制。

![menu-menu](https://user-images.githubusercontent.com/6487389/159390946-dd7c21c1-9c22-4a9d-b2a6-da50b1b0476c.png)

页面的右上角 import 和 Export 是其他属性控制的，感觉还行，就没有修改。

添加以下 CSS 片段：

```css
.vertical-tab-nav-item {
    padding: 4px 6px 4px 18px;
    font-size: 14px;
    font-family: "Sarasa UI SC";
}
.setting-item-name {
    font-size: 14px;
}
```
启用后，效果如下：

![menu-style-modify](https://user-images.githubusercontent.com/6487389/159392502-31e73bb8-ba41-4ffb-84c5-7505c7f919a3.png)
