### ISSUE TITLE
Can content in outline be non-wrap？

### ISSUE THREAD

**Issue by FongTsang** [whyt-byte/Blue-Topaz_Obsidian-css#338]
Dear creators, I wonder is there anyway to let title in outline panel be non-wrap style (show only one line with no wrap), sometimes my title can very long which lead to a awkward situation that the whole outline panel is occupied by one title. I desire the panel can show as much title items as it can.
![图片](https://user-images.githubusercontent.com/53118840/175223518-c3e9d23c-47ad-46ff-b3ed-c9abe36c118a.png)

**Comment by cumany** [comment]
Try this css snippet

```css
.workspace-leaf-content[data-type="outline"] .tree-item
{
  word-spacing: normal;
  word-break: normal;
  word-wrap: break-word;
  white-space: pre;
 overflow:auto;
}

```
