### ISSUE TITLE
编辑状态下，引用文本选中仍存在一点问题

### ISSUE THREAD

**Issue by PaulHerrero** [whyt-byte/Blue-Topaz_Obsidian-css#34]
更新了最新的css后，在编辑状态下可以看到引用文本中选中哪些文字了，但选中时显示的高光会偏移，如
![Snipaste_2021-01-04_13-54-28](https://user-images.githubusercontent.com/56058332/103505143-834e3880-4e94-11eb-983b-24279087ec91.png)， 但实际选中的是 m 。

希望可以选择在编辑状态下，鼠标离开引用文本时不自动渲染效果

---
另一个小问题，更新后，侧边栏的箭头和文件夹名重叠了。不知道是不是因为自定义了字号的原因，但前一版本的css未出现这个问题
![Snipaste_2021-01-04_13-49-57](https://user-images.githubusercontent.com/56058332/103505453-37e85a00-4e95-11eb-8adf-5ab79b1f1458.png)
![Snipaste_2021-01-04_13-50-11](https://user-images.githubusercontent.com/56058332/103505457-39198700-4e95-11eb-8b60-b427232096d9.png)

**Comment by whyt-byte** [comment]
先回答后面那个，估计你是0.10.5之前的版本，因为软件更新，开发者更改了部分设置，现在的css适配的是0.10.5，你可以在releases里找个老版本的用，软件更新了再用新版。

引用框等会给你个css片段，在软件里启用片段就行

**Comment by PaulHerrero** [comment]
好的，感谢

**Comment by whyt-byte** [comment]
复制这个css片段，在软件里启用。

```css
div:not(.CodeMirror-activeline)>.CodeMirror-line span.cm-formatting-quote, .CodeMirror-line span.cm-formatting-quote {
    color: var(--text-accent) !important;
}
  
div:not(.CodeMirror-activeline)>.HyperMD-quote {
    border-left: none;
    margin-left: 0px;
}
```
