### ISSUE TITLE
请教一下，关于 tag-pill 和颜色

### ISSUE THREAD

**Issue by zhao414** [whyt-byte/Blue-Topaz_Obsidian-css#364]
目前的彩色的 tag-pill 很好看，不过，我看目前的主题是根据一个 tag 在一行中是第几个出现的，来给 tag-pill 指定颜色。

我想要给特定的 tag，指定特定的颜色的 tag-pill，目前的主题支持这个功能么？

我看了

https://forum.obsidian.md/t/any-way-to-auto-highlight-specific-text/41226/2

这个 css snippet 可以给指定的 tag （例子中 `#now` 和 `#next`）配置指定的颜色：
```css
.cm-s-obsidian span.cm-hashtag.cm-tag-now {
  color:green;
}
.cm-s-obsidian span.cm-hashtag.cm-tag-next {
  color:orange;
}
```

我想请教一下：

我想用 tag-pill，如何将 tag 变成 tag-pill？

**Comment by cumany** [comment]
```css
body.tag-pill-outlined .cm-s-obsidian span.cm-hashtag-begin.cm-tag-now, 
body.tag-pill-outlined .cm-s-obsidian span.cm-hashtag-begin+.cm-hashtag.cm-meta.cm-tag-now {
  color: green !important;
}

body.tag-pill-outlined .cm-s-obsidian span.cm-hashtag-begin.cm-tag-next, 
body.tag-pill-outlined .cm-s-obsidian span.cm-hashtag-begin+.cm-hashtag.cm-meta.cm-tag-next {
  color: orange !important;
}
 
```
