### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by thremaana** [whyt-byte/Blue-Topaz_Obsidian-css#405]
All features of your theme are highly appreciable. I have a suggestion. Kindly check the "tag" style of  themes called "WiseLight" & "SparklingWisdom" in obsidian themes, their "tag" styles are excellent. Can you include such tags in "Blue-Topaz" theme also? sure it will make blue -topazz theme more beautiful

**Comment by cumany** [comment]
2.3.17  Tag style  Set to default with style setting  plugin
Then the following code is saved as a css snippet and enabled
```css


/*from Sparkling Wisdom theme ******/
  
.theme-light .tag {
  background-color:lavenderblush !important;
  color: darkred ;
  border: solid ;
  font-size: 0.85em ;
  font-weight: 600 ;
  padding: 1px 8px ;
  text-align: center ;
  text-decoration: none ;
  display: inline-block ;
  margin: 0px 0px ;
  cursor: pointer ;
  border-radius: 14px ;
}

.theme-light .tag:hover {
    background-color:lavenderblush !important;
    color: darkred ;
    border: solid ;
    font-size: 0.85em ;
    font-weight: 600 ;
    padding: 1px 8px ;
    text-align: center ;
    text-decoration: none ;
    display: inline-block ;
    margin: 0px 0px ;
    cursor: pointer ;
    border-radius: 14px ;

}

.theme-light .tag:before {
    background: darkred !important;
    width: 10px;
    height: 10px;
    content: "";
    display: inline-block;
    border-radius: 20px;
    box-shadow: inset 0px 2px 5px rgba(0,0,0,0.2);
    margin: 0 5px 0 0;
    transition: background 0.5s ease-out 200ms;
}

.theme-light .tag:after {
    background: darkred !important;
    width: 10px;
    height: 10px;
    content: "";
    display: none;
    border-radius: 20px;
    box-shadow: inset 0px 2px 5px rgba(0,0,0,0.2);
    margin: 0 5px;
} 


.theme-light .tag:hover:before { 
    background: lavenderblush !important;
    width: 0px;
    height: 0px;
    border-radius: 0px;
}

.theme-light .tag:hover:after { 
    display: inline-block;
}

.theme-dark .tag {
  background-color: PaleTurquoise !important;
  color:  black;
  border:2px solid;
  border-color:turquoise;
  font-size: 0.85em;
  font-weight: 600;
  padding: 1px 8px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  margin: 0px 0px;
  cursor: pointer;
  border-radius: 14px;
}


.theme-dark .tag:before {
    background: #000 !important;
    width: 10px;
    height: 10px;
    content: "";
    display: inline-block;
    border-radius: 20px;
    box-shadow: inset 0px 2px 5px rgba(0,0,0,0.2);
    margin: 0 5px 0 0;
    transition: background 0.5s ease-out 200ms;
}

.theme-dark .tag:after {
    background: #000 !important;
    width: 10px;
    height: 10px;
    content: "";
    display: none;
    border-radius: 20px;
    box-shadow: inset 0px 2px 5px rgba(0,0,0,0.2);
    margin: 0 5px;
}

 
.theme-dark .tag:hover {
  background-color: PaleTurquoise !important;
  color:  black;
  border:2px solid;
  border-color:turquoise;
  font-size: 0.85em;
  font-weight: 600;
  padding: 1px 8px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  margin: 0px 0px;
  cursor: pointer;
  border-radius: 14px;
}

.theme-dark .tag:hover:before { 
    background: PaleTurquoise !important ;
    width: 0px;
    height: 0px;
    border-radius: 0px;
}

.theme-dark .tag:hover:after { 
    display: inline-block;
}


```
