### ISSUE TITLE
是否可以禁止大纲和文件列表中内容换行？

### ISSUE THREAD

**Issue by lartpang** [whyt-byte/Blue-Topaz_Obsidian-css#406]
![图片](https://user-images.githubusercontent.com/26847524/193968794-d5b5faa4-82e8-448e-a609-d0137a973d38.png)

类似这样的内容目前会换行显示，导致整个列表显得及其冗长。

而且文件的大纲也存在这样的问题。

Minimal主题里有这样的设定，不知这个主题是否会支持一下相关功能？

**Comment by cumany** [comment]
安装ste setting 插件 2.3.3设置

**Comment by lartpang** [comment]
@cumany 
多谢，这个可以调整文件目录的格式，但是如果我还想调整文件大纲的话又该如何呢？

**Comment by cumany** [comment]
大纲没有调整选项 但可以用下面片段实现
```css
.outline .tree-item-inner {
    white-space: nowrap;
}
```
