### ISSUE TITLE
Fix notification layout

### ISSUE THREAD

**Issue by linqingyao** [whyt-byte/Blue-Topaz_Obsidian-css#493]
This is a fix for the #492  issue. 
Replace the Settings in the theme file with the following snippets:
```css
.notice-container {
  z-index: var(--layer-notice);
  position: fixed;
  top: 40px;
  right: 0px;
  padding: 0px;
  overflow: hidden;
}
```
