### ISSUE TITLE
Hide [[]] for links in edit mode

### ISSUE THREAD

**Issue by KhongSao** [whyt-byte/Blue-Topaz_Obsidian-css#50]

**Comment by KhongSao** [comment]
Love the theme - will be using this going forward.

For backlinks - is there a way for the backlink to show without the [[black link A]] [[black link B]] pages showing - could they show up in preview mode rather than edit mode for instance? such as black link A black link B  ( without the [[]] )

I just want to avoid having as many characters on the screen as possible

**Comment by whyt-byte** [comment]
Thank you for loving it. Please use the following code to create a css snippet and activate the snippet in Obsidian. Enjoy!
```css
div:not(.CodeMirror-activeline) > .CodeMirror-line span.cm-formatting-link:not(.cm-hmd-footnote):not(.cm-footref) { 
display: none; 
}
```
