### ISSUE TITLE
魔方主题导出pdf文字颜色问题

### ISSUE THREAD

**Issue by duoml** [whyt-byte/Blue-Topaz_Obsidian-css#509]
![image](https://user-images.githubusercontent.com/17494027/217552914-be868c7b-e0f4-4a83-87d9-e4cf5099f335.png)
文本颜色为interactive-accent的颜色

预览模式下的颜色：
![image](https://user-images.githubusercontent.com/17494027/217553380-f0d3660b-4fb6-4ac2-b83c-46f210d52638.png)

**Comment by duoml** [comment]
在snippets中修改后正常
```css
.print {
    --normal-text: #3EAF7C;
    --interactive-accent:#34495E;
}
```
![image](https://user-images.githubusercontent.com/17494027/217553699-2e7bba07-5add-4e1f-92b0-987adc7613b3.png)
