### ISSUE TITLE
文字对齐的命令不管用了？

### ISSUE THREAD

**Issue by zhl111** [whyt-byte/Blue-Topaz_Obsidian-css#57]
<p align="right">  xxxxx </p>这样的命令在别的css里没问题，咱的似乎不起作用？还有图片我不想居中，但也没法修改

**Comment by whyt-byte** [comment]
请描述是“文字对齐”是什么。

取消图片居中，使用以下片段：
```css
.view-content img:not([class="emoji"]) {
  display: inline;
}
```
