### ISSUE TITLE
bug？

### ISSUE THREAD

**Issue by zhl111** [whyt-byte/Blue-Topaz_Obsidian-css#58]
![image](https://user-images.githubusercontent.com/29135984/112487962-1de55600-8db8-11eb-88cf-e34e7e0e1bb0.png)
![image](https://user-images.githubusercontent.com/29135984/112487985-22aa0a00-8db8-11eb-89a7-a6e9e25b3d96.png)
加了引用，结果理想国和书名号之间有一个大空档，去掉引用就没问题

**Comment by whyt-byte** [comment]
无法复现，而且下面那个图不是Blue Topaz的引用框。请检查并关闭以下按钮，看看是否可行。
![image](https://user-images.githubusercontent.com/72023275/112569564-65eb9380-8e1f-11eb-8592-23a469110d37.png)

**Comment by zhl111** [comment]
嗯，是外框的事情。这个外框好像也是从您的github里提到过的

**Comment by whyt-byte** [comment]
那个太古老了，是我做着玩的，没有对现在的主题进行适配

**Comment by whyt-byte** [comment]
修改了一下，使用以下片段：
```css
/* Blockquote header */
.markdown-preview-view blockquote {
  position: relative; /* for pseudos */
  color: var(--theme-color);
  font-size: 1rem;
  font-weight: normal;
  line-height: 1.5;
  margin: 0;
  border: 3px solid;
  border-radius:20px;
  padding: 10px 15px;
  background: var(--background-primary);
}

.theme-dark .markdown-preview-view blockquote {
  background-color: var(--background-primary) !important;
}

.markdown-preview-view blockquote p{
 color: var(--text-normal);
 font-size: 16px;
}

.markdown-preview-view blockquote:after {
  content:"";
  position: absolute;
  border: 3px solid var(--theme-color);
  border-radius: 35px 0 0 0;
  width: 50px;
  height: 55px;
  bottom: -58px;
  left: 25px;
  border-bottom: none;
  border-left: none;
  border-right: none;
  z-index: 3; 
}

.markdown-preview-view blockquote:before {
  content:"";
  position: absolute;
  width: 25px;
  border: 10px solid var(--background-primary);
  bottom: -7px;
  left: 20px;
  z-index: 2;
}
```
