### ISSUE TITLE
代码块字体设置

### ISSUE THREAD

**Issue by wanghusw** [whyt-byte/Blue-Topaz_Obsidian-css#72]
你好，代码块的字体设置是在哪一行呢，想将其设置为有无衬线中文字体的字体。

**Comment by whyt-byte** [comment]
可以新建一个css片段，使用下方代码，更改你要的字体，放在.obsidian/snippets文件夹内
```css
:root {
--font-monospace: 你要的字体;
}
```
