### ISSUE TITLE
建议H1-H5字体和文本统一

### ISSUE THREAD

**Issue by jiangaq** [whyt-byte/Blue-Topaz_Obsidian-css#77]
现在H1-H4好象是黑体，和正文的文楷不统一，感觉不太匹配

**Comment by whyt-byte** [comment]
有意这么设置的，可以自行做统一处理

**Comment by whyt-byte** [comment]
可以使用下列片段统一字体
```css
.cm-header-1,
.cm-header-2,
.cm-header-3,
.cm-header-4,
.cm-header-5,
.cm-header-6,
.markdown-preview-view h1,
.markdown-preview-view h2,
.markdown-preview-view h3
.markdown-preview-view h4
.markdown-preview-view h5
.markdown-preview-view h6 {
    font-family: var(--font-family-major);
}
```
