### ISSUE TITLE
如何修改字体？

### ISSUE THREAD

**Issue by drrrMikado** [whyt-byte/Blue-Topaz_Obsidian-css#8]
像正文的中文，想修改成：苹方/思源黑体等其他字体，英文想修改成：Monaco，这样是要如何修改？
假如还想要修改（增大）全局中文的字间距的话，需要如何修改呢？
谢谢解答

**Comment by whyt-byte** [comment]
正文字体：在`pre.CodeMirror-line{}`和`p{}`里加入`font-family:;`加上你需要的字体。在`pre.CodeMirror-line{}`设置字体要加上`!important`，如

```css
pre.CodeMirror-line{
  font-family: Monaco, 思源黑体 !important;
}
```

你说的字间距全局只是正文吗？只是正文也在`pre.CodeMirror-line{}`和`p{}`里加入并设置`line-height:;`。如果“全局”指所有地方（标题、引用等），那修改不了，必须逐项设置。
