### ISSUE TITLE
想请问下如何在snippets里关掉背景图片

### ISSUE THREAD

**Issue by PaulHerrero** [whyt-byte/Blue-Topaz_Obsidian-css#80]

**Comment by whyt-byte** [comment]
你好，可以使用下面的代码创建snippet，用来移除背景。很遗憾你不喜欢这些背景图片。
```css
.workspace-split.mod-root .workspace-leaf:nth-child(n) .workspace-leaf-content:not([data-type="outline"])::before {
  display: none;
  position: unset;
}
```
